version: '3.1'

services:
    api-search:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        network_mode: 'host'
        mem_limit: 750m
        volumes:
            - .:/var/www/html
        environment:
            APACHE_PORT: 8001

